//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_About {
            get {
                return ResourceManager.GetString("Command_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Apply {
            get {
                return ResourceManager.GetString("Command_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Cancel {
            get {
                return ResourceManager.GetString("Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大文字と小文字を区別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CaseSensitive {
            get {
                return ResourceManager.GetString("Command_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字コードを変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ChangeEncoding {
            get {
                return ResourceManager.GetString("Command_ChangeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンタックス定義を変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ChangeSyntax {
            get {
                return ResourceManager.GetString("Command_ChangeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CloseAll {
            get {
                return ResourceManager.GetString("Command_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他をすべて閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CloseOther {
            get {
                return ResourceManager.GetString("Command_CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーディング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Coding {
            get {
                return ResourceManager.GetString("Command_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード補完 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Completion {
            get {
                return ResourceManager.GetString("Command_Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンテンツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Contents {
            get {
                return ResourceManager.GetString("Command_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空白をタブに変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertSpacesToTabs {
            get {
                return ResourceManager.GetString("Command_ConvertSpacesToTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タブを空白に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("Command_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小文字に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToLowerCase {
            get {
                return ResourceManager.GetString("Command_ConvertToLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToNarrow {
            get {
                return ResourceManager.GetString("Command_ConvertToNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語の先頭を大文字に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToTitleCase {
            get {
                return ResourceManager.GetString("Command_ConvertToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大文字に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToUpperCase {
            get {
                return ResourceManager.GetString("Command_ConvertToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角に変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToWide {
            get {
                return ResourceManager.GetString("Command_ConvertToWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全パスをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CopyFullPath {
            get {
                return ResourceManager.GetString("Command_CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Creator {
            get {
                return ResourceManager.GetString("Command_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Cut {
            get {
                return ResourceManager.GetString("Command_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Diff {
            get {
                return ResourceManager.GetString("Command_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未変更のものと比較 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DiffUnmodified {
            get {
                return ResourceManager.GetString("Command_DiffUnmodified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   寄付する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Donate {
            get {
                return ResourceManager.GetString("Command_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Execute {
            get {
                return ResourceManager.GetString("Command_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Exit {
            get {
                return ResourceManager.GetString("Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを終了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ExitApplication {
            get {
                return ResourceManager.GetString("Command_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスプローラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Explorer {
            get {
                return ResourceManager.GetString("Command_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルを出力する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ExportLog {
            get {
                return ResourceManager.GetString("Command_ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定のエクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ExportSettings {
            get {
                return ResourceManager.GetString("Command_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_File {
            get {
                return ResourceManager.GetString("Command_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Find {
            get {
                return ResourceManager.GetString("Command_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_FindNext {
            get {
                return ResourceManager.GetString("Command_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_FindPrev {
            get {
                return ResourceManager.GetString("Command_FindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードを折りたたむ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Folding {
            get {
                return ResourceManager.GetString("Command_Folding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Formatting {
            get {
                return ResourceManager.GetString("Command_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定行へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_GoToLine {
            get {
                return ResourceManager.GetString("Command_GoToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Help {
            get {
                return ResourceManager.GetString("Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定のインポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ImportSettings {
            get {
                return ResourceManager.GetString("Command_ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定の初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_InitializeSettings {
            get {
                return ResourceManager.GetString("Command_InitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンタックス定義を初期化する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_InitializeSyntax {
            get {
                return ResourceManager.GetString("Command_InitializeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウを集約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MergeWindows {
            get {
                return ResourceManager.GetString("Command_MergeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次ページへ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveDownByPage {
            get {
                return ResourceManager.GetString("Command_MoveDownByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語の先頭へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveLeftByWord {
            get {
                return ResourceManager.GetString("Command_MoveLeftByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Movement {
            get {
                return ResourceManager.GetString("Command_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語の末尾へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveRightByWord {
            get {
                return ResourceManager.GetString("Command_MoveRightByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの末尾へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToDocumentEnd {
            get {
                return ResourceManager.GetString("Command_MoveToDocumentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの先頭へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToDocumentStart {
            get {
                return ResourceManager.GetString("Command_MoveToDocumentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行末へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToLineEnd {
            get {
                return ResourceManager.GetString("Command_MoveToLineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行頭へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToLineStart {
            get {
                return ResourceManager.GetString("Command_MoveToLineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前ページへ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveUpByPage {
            get {
                return ResourceManager.GetString("Command_MoveUpByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ウィンドウ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_NewWindow {
            get {
                return ResourceManager.GetString("Command_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_No {
            get {
                return ResourceManager.GetString("Command_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_OK {
            get {
                return ResourceManager.GetString("Command_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Open {
            get {
                return ResourceManager.GetString("Command_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親フォルダを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_OpenParentDirectory {
            get {
                return ResourceManager.GetString("Command_OpenParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスプローラーで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_OpenWithExplorer {
            get {
                return ResourceManager.GetString("Command_OpenWithExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Option {
            get {
                return ResourceManager.GetString("Command_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Paste {
            get {
                return ResourceManager.GetString("Command_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Print {
            get {
                return ResourceManager.GetString("Command_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_PrintPreview {
            get {
                return ResourceManager.GetString("Command_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Property {
            get {
                return ResourceManager.GetString("Command_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Redo {
            get {
                return ResourceManager.GetString("Command_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Replace {
            get {
                return ResourceManager.GetString("Command_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ReplaceAll {
            get {
                return ResourceManager.GetString("Command_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ReplaceNext {
            get {
                return ResourceManager.GetString("Command_ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Repository {
            get {
                return ResourceManager.GetString("Command_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SaveAll {
            get {
                return ResourceManager.GetString("Command_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SaveAs {
            get {
                return ResourceManager.GetString("Command_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# スクリプトランナー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ScriptRunner {
            get {
                return ResourceManager.GetString("Command_ScriptRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectAll {
            get {
                return ResourceManager.GetString("Command_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次ページまで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectDownByPage {
            get {
                return ResourceManager.GetString("Command_SelectDownByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Selection {
            get {
                return ResourceManager.GetString("Command_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語の先頭まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectLeftByWord {
            get {
                return ResourceManager.GetString("Command_SelectLeftByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単語の末尾まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectRightByWord {
            get {
                return ResourceManager.GetString("Command_SelectRightByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの末尾まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToDocumentEnd {
            get {
                return ResourceManager.GetString("Command_SelectToDocumentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの先頭まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToDocumentStart {
            get {
                return ResourceManager.GetString("Command_SelectToDocumentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行末まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToLineEnd {
            get {
                return ResourceManager.GetString("Command_SelectToLineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行頭まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToLineStart {
            get {
                return ResourceManager.GetString("Command_SelectToLineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前ページまで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectUpByPage {
            get {
                return ResourceManager.GetString("Command_SelectUpByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Show {
            get {
                return ResourceManager.GetString("Command_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニューバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowMenuBar {
            get {
                return ResourceManager.GetString("Command_ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイドバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowSideBar {
            get {
                return ResourceManager.GetString("Command_ShowSideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowStatusBar {
            get {
                return ResourceManager.GetString("Command_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowToolBar {
            get {
                return ResourceManager.GetString("Command_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索モードと置換モードの切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SwitchFindMode {
            get {
                return ResourceManager.GetString("Command_SwitchFindMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全画面表示とウィンドウ表示の切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SwitchFullScreenMode {
            get {
                return ResourceManager.GetString("Command_SwitchFullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターミナル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Terminal {
            get {
                return ResourceManager.GetString("Command_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Tools {
            get {
                return ResourceManager.GetString("Command_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面に表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Topmost {
            get {
                return ResourceManager.GetString("Command_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Undo {
            get {
                return ResourceManager.GetString("Command_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードを展開する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Unfolding {
            get {
                return ResourceManager.GetString("Command_Unfolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現を使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UseRegex {
            get {
                return ResourceManager.GetString("Command_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_View {
            get {
                return ResourceManager.GetString("Command_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_WindowList {
            get {
                return ResourceManager.GetString("Command_WindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面構成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_WindowStructure {
            get {
                return ResourceManager.GetString("Command_WindowStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Yes {
            get {
                return ResourceManager.GetString("Command_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Zoom {
            get {
                return ResourceManager.GetString("Command_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomIn {
            get {
                return ResourceManager.GetString("Command_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縮小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomOut {
            get {
                return ResourceManager.GetString("Command_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomReset {
            get {
                return ResourceManager.GetString("Command_ZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CPP {
            get {
                object obj = ResourceManager.GetObject("CPP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CSharp {
            get {
                object obj = ResourceManager.GetObject("CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Java {
            get {
                object obj = ResourceManager.GetObject("Java", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] JavaScript {
            get {
                object obj = ResourceManager.GetObject("JavaScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] JSON {
            get {
                object obj = ResourceManager.GetObject("JSON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   アクセス日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AccessDate {
            get {
                return ResourceManager.GetString("Label_AccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AllFiles {
            get {
                return ResourceManager.GetString("Label_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AppDataDirectory {
            get {
                return ResourceManager.GetString("Label_AppDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Attributes {
            get {
                return ResourceManager.GetString("Label_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動検出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AutoDetect {
            get {
                return ResourceManager.GetString("Label_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動保存の間隔(分) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AutoSaveInterval {
            get {
                return ResourceManager.GetString("Label_AutoSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目安線の位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnRulerPosition {
            get {
                return ResourceManager.GetString("Label_ColumnRulerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Command {
            get {
                return ResourceManager.GetString("Label_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   構成ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ConfigFile {
            get {
                return ResourceManager.GetString("Label_ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Confirm {
            get {
                return ResourceManager.GetString("Label_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CreationDate {
            get {
                return ResourceManager.GetString("Label_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Culture {
            get {
                return ResourceManager.GetString("Label_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   黒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Dark {
            get {
                return ResourceManager.GetString("Label_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比較先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_DiffDestination {
            get {
                return ResourceManager.GetString("Label_DiffDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比較元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_DiffSource {
            get {
                return ResourceManager.GetString("Label_DiffSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Encoding {
            get {
                return ResourceManager.GetString("Label_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ExecutionDirectory {
            get {
                return ResourceManager.GetString("Label_ExecutionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ExecutionFile {
            get {
                return ResourceManager.GetString("Label_ExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスプローラーの起点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ExplorerRoot {
            get {
                return ResourceManager.GetString("Label_ExplorerRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Font {
            get {
                return ResourceManager.GetString("Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Format {
            get {
                return ResourceManager.GetString("Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タブ幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_IndentationSize {
            get {
                return ResourceManager.GetString("Label_IndentationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_IsEnabled {
            get {
                return ResourceManager.GetString("Label_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   白 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Light {
            get {
                return ResourceManager.GetString("Label_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LineMumber {
            get {
                return ResourceManager.GetString("Label_LineMumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   場所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiredDate {
            get {
                return ResourceManager.GetString("Label_ModifiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Notify {
            get {
                return ResourceManager.GetString("Label_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_OtherTools {
            get {
                return ResourceManager.GetString("Label_OtherTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所有者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Owner {
            get {
                return ResourceManager.GetString("Label_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SearchPattern {
            get {
                return ResourceManager.GetString("Label_SearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SearchText {
            get {
                return ResourceManager.GetString("Label_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SettingFile {
            get {
                return ResourceManager.GetString("Label_SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムに連動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SyncAppTheme {
            get {
                return ResourceManager.GetString("Label_SyncAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンタックス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Syntax {
            get {
                return ResourceManager.GetString("Label_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SystemDirectory {
            get {
                return ResourceManager.GetString("Label_SystemDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SystemSettings {
            get {
                return ResourceManager.GetString("Label_SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TempDirectory {
            get {
                return ResourceManager.GetString("Label_TempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストエディタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TextEditor {
            get {
                return ResourceManager.GetString("Label_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Warn {
            get {
                return ResourceManager.GetString("Label_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終行を超えたスクロールを許可する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_AllowScrollBelowDocument {
            get {
                return ResourceManager.GetString("LabelText_AllowScrollBelowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景を透過する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_AllowsTransparency {
            get {
                return ResourceManager.GetString("LabelText_AllowsTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きモードへの切り替えを許可する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_AllowToggleOverstrikeMode {
            get {
                return ResourceManager.GetString("LabelText_AllowToggleOverstrikeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既定で自動検出する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_AutoDetectByDefault {
            get {
                return ResourceManager.GetString("LabelText_AutoDetectByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タブをスペースに変換して入力する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("LabelText_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワードの自動補完を有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableAutoCompletion {
            get {
                return ResourceManager.GetString("LabelText_EnableAutoCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のファイルを一時フォルダに自動保存する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableAutoSave {
            get {
                return ResourceManager.GetString("LabelText_EnableAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未選択状態でのコピーと切り取りを可能にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableCutCopyWholeLine {
            get {
                return ResourceManager.GetString("LabelText_EnableCutCopyWholeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスのハイパーリンクを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableEmailHyperlinks {
            get {
                return ResourceManager.GetString("LabelText_EnableEmailHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードの折り畳みを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableFoldings {
            get {
                return ResourceManager.GetString("LabelText_EnableFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLのハイパーリンクを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableHyperlinks {
            get {
                return ResourceManager.GetString("LabelText_EnableHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMEサポートを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableImeSupport {
            get {
                return ResourceManager.GetString("LabelText_EnableImeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知領域アイコンを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableNotificationIcon {
            get {
                return ResourceManager.GetString("LabelText_EnableNotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   矩形選択を有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableRectangularSelection {
            get {
                return ResourceManager.GetString("LabelText_EnableRectangularSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知領域に常駐する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableResident {
            get {
                return ResourceManager.GetString("LabelText_EnableResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドラッグ アンド ドロップ 編集を有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableTextDragDrop {
            get {
                return ResourceManager.GetString("LabelText_EnableTextDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フリーカーソルを有効にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableVirtualSpace {
            get {
                return ResourceManager.GetString("LabelText_EnableVirtualSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右端で折り返して表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_EnableWordWrap {
            get {
                return ResourceManager.GetString("LabelText_EnableWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力中はカーソルを非表示にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_HideCursorWhileTyping {
            get {
                return ResourceManager.GetString("LabelText_HideCursorWhileTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在の行を強調する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_HighlightCurrentLine {
            get {
                return ResourceManager.GetString("LabelText_HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハイパーリンクの選択に[Ctrl]キーを要求する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("LabelText_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウの位置を保存する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_SaveWindowPlacement {
            get {
                return ResourceManager.GetString("LabelText_SaveWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御文字を表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowBoxForControlCharacters {
            get {
                return ResourceManager.GetString("LabelText_ShowBoxForControlCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更行を示すマーカーを表示にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowChangeMarker {
            get {
                return ResourceManager.GetString("LabelText_ShowChangeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目安線を表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowColumnRuler {
            get {
                return ResourceManager.GetString("LabelText_ShowColumnRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行を表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowEndOfLine {
            get {
                return ResourceManager.GetString("LabelText_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのアイコンを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowFileIcon {
            get {
                return ResourceManager.GetString("LabelText_ShowFileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの完全パスを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowFullName {
            get {
                return ResourceManager.GetString("LabelText_ShowFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff ビューアーをインラインで表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowInlineDiffViewer {
            get {
                return ResourceManager.GetString("LabelText_ShowInlineDiffViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行番号を表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowLineNumbers {
            get {
                return ResourceManager.GetString("LabelText_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニューバーを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowMenuBar {
            get {
                return ResourceManager.GetString("LabelText_ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単一タブを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowSingleTab {
            get {
                return ResourceManager.GetString("LabelText_ShowSingleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペースを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowSpaces {
            get {
                return ResourceManager.GetString("LabelText_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスバーを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowStatusBar {
            get {
                return ResourceManager.GetString("LabelText_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タブを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowTabs {
            get {
                return ResourceManager.GetString("LabelText_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールバーを表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_ShowToolBar {
            get {
                return ResourceManager.GetString("LabelText_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ内のトースト通知を使用にする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_UseInAppToastNotifications {
            get {
                return ResourceManager.GetString("LabelText_UseInAppToastNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイダイアログを使用する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelText_UseOverlayDialog {
            get {
                return ResourceManager.GetString("LabelText_UseOverlayDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] MarkDown {
            get {
                object obj = ResourceManager.GetObject("MarkDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   ログファイルを削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmCleanUpLog {
            get {
                return ResourceManager.GetString("Message_ConfirmCleanUpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容は破棄されます。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmDiscardChanges {
            get {
                return ResourceManager.GetString("Message_ConfirmDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定を初期化します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmInitializeSettings {
            get {
                return ResourceManager.GetString("Message_ConfirmInitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンタックス定義を初期化します。
        ///定義ファイルは既定のものに置き換えられます。
        ///設定は次回起動時に反映されます。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmInitializeSyntax {
            get {
                return ResourceManager.GetString("Message_ConfirmInitializeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大きなファイルは開くまでに長い時間がかかる場合があります。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmOpenLargeFile {
            get {
                return ResourceManager.GetString("Message_ConfirmOpenLargeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定を上書きします。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmOverrideSettings {
            get {
                return ResourceManager.GetString("Message_ConfirmOverrideSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmSaveChanges {
            get {
                return ResourceManager.GetString("Message_ConfirmSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時ファイルに保存されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyAutoSaved {
            get {
                return ResourceManager.GetString("Message_NotifyAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去にキャッシュされたファイルが見つかりました。
        ///ご確認頂き、不要なファイルを削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyCachedFilesRemain {
            get {
                return ResourceManager.GetString("Message_NotifyCachedFilesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたフォルダは見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyDirectoryNotFound {
            get {
                return ResourceManager.GetString("Message_NotifyDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   気に入って頂けましたら、継続開発のためのご寄付も歓迎いたします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyDonate {
            get {
                return ResourceManager.GetString("Message_NotifyDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストにエラーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyErrorText {
            get {
                return ResourceManager.GetString("Message_NotifyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別のタブがこのファイルを開いています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyFileInAnother {
            get {
                return ResourceManager.GetString("Message_NotifyFileInAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このファイルは書き込みが禁止されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyFileLocked {
            get {
                return ResourceManager.GetString("Message_NotifyFileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F11 を押して全画面表示を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyFullScreenMode {
            get {
                return ResourceManager.GetString("Message_NotifyFullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストを読み込みました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyLoaded {
            get {
                return ResourceManager.GetString("Message_NotifyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された文字列は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyNoMatchesText {
            get {
                return ResourceManager.GetString("Message_NotifyNoMatchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifySaved {
            get {
                return ResourceManager.GetString("Message_NotifySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時的に利用できません。時間を置いて再度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyTryAgainLater {
            get {
                return ResourceManager.GetString("Message_NotifyTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ver. {1} へようこそ。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyWelcome {
            get {
                return ResourceManager.GetString("Message_NotifyWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] PHP {
            get {
                object obj = ResourceManager.GetObject("PHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] PLSQL {
            get {
                object obj = ResourceManager.GetObject("PLSQL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Python {
            get {
                object obj = ResourceManager.GetObject("Python", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   ドキュメントが空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EmptyDocument {
            get {
                return ResourceManager.GetString("Text_EmptyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この項目は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_RequiredField {
            get {
                return ResourceManager.GetString("Text_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一のテキストです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SameTexts {
            get {
                return ResourceManager.GetString("Text_SameTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しばらくお待ちください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Working {
            get {
                return ResourceManager.GetString("Text_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] TransactSQL {
            get {
                object obj = ResourceManager.GetObject("TransactSQL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] VisualBasic {
            get {
                object obj = ResourceManager.GetObject("VisualBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] XML {
            get {
                object obj = ResourceManager.GetObject("XML", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
