name: Build and Release

on:
  push:
    tags:
      - 'v*' # "v" から始まるタグ名

jobs:
  build:
    env:
      Project_Directory: MyPad
      Project_Path:      MyPad/MyPad.csproj
      Test_Project_Path: MyPad.Test/MyPad.Test.csproj
    
    strategy:
      matrix:
        os: [ windows-latest ]
        configuration: [ Release ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Test
      run: dotnet test $env:Test_Project_Path -p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    
    - name: Build
      run: dotnet build $env:Test_Project_Path -p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
