name: Build and Release

on:
  push:
    tags:
      - 'v*' # "v" から始まるタグ名

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: 6.0.x
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build app
      run: dotnet build MyPad/MyPad.csproj -c Release

    - name: Build test
      run: dotnet build MyPad.Test/MyPad.Test.csproj -c Release --no-dependencies

    - name: Test
      run: dotnet test MyPad.Test/MyPad.Test.csproj --no-restore

    - name: Copy
      shell: pwsh
      run: |
        mkdir dist
        Copy-Item -Path MyPad/bin/Release/* -Destination dist -Recurse

    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

  create-release:
    needs: [build]
    runs-on: windows-latest
    steps:

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Compress
        shell: pwsh
        run: |
          Compress-Archive -Path dist/* -DestinationPath release.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
