on:
  push:
    tags:
      - 'v*' # "v" から始まるタグが付与されたとき

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: 6.0.x

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Apps
        run: dotnet build MyPad/MyPad.csproj -c Release

      - name: Build Tests
        run: dotnet build MyPad.Test/MyPad.Test.csproj -c Release --no-dependencies

      - name: Unit Test
        run: dotnet test MyPad.Test/MyPad.Test.csproj --no-restore

      - name: Move to dist
        shell: pwsh
        run: |
          mkdir dist
          Copy-Item -Path MyPad/bin/Release/* -Destination dist -Recurse

      - name: Archive Apps
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Notify Result
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  release:
    needs: [build]
    runs-on: windows-latest

    steps:
      - name: Download Apps
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Compress Apps
        shell: pwsh
        run: |
          Compress-Archive -Path dist/* -DestinationPath release.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Publish Release
        uses: actions/upload-release-asset@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip

      - name: Notify Result
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
